### ISSUE TITLE
Det skall gå att använda verktyget på alla skärmstorlekar ner till 360px i bredd. (G)

### ISSUE THREAD

**Issue by gabriel-lugo** [plugga-tech/kalenderverktyg-med-javascript-ghe#9]

**Comment by Emil-Helge** [comment]
Vi lämnade ärendet uppe ifall att ändringar från andra ärenden skulle leda till att verktyget inte längre är responsivt och stänger nu det när vi är säkra på att det inte finns någon risk att det ska påverkas längre.
